-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 13:19:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mediamarktdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mediamarktdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediamarktdb` DEFAULT CHARACTER SET utf8 ;
USE `mediamarktdb` ;

-- -----------------------------------------------------
-- Table `mediamarktdb`.`landen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`landen` (
  `idland` INT NOT NULL AUTO_INCREMENT,
  `landnaam` VARCHAR(255) NULL,
  `afkortingnaam` VARCHAR(255) NULL,
  PRIMARY KEY (`idland`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`categorieën`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`categorieën` (
  `idcategorie` INT NOT NULL AUTO_INCREMENT,
  `categorienaam` VARCHAR(255) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`leveranciers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`leveranciers` (
  `idleverancier` INT NOT NULL AUTO_INCREMENT,
  `leveranciernaam` VARCHAR(45) NULL,
  `producten` VARCHAR(45) NULL,
  `landen_idland` INT NOT NULL,
  PRIMARY KEY (`idleverancier`),
  INDEX `fk_leveranciers_landen1_idx` (`landen_idland` ASC) VISIBLE,
  CONSTRAINT `fk_leveranciers_landen1`
    FOREIGN KEY (`landen_idland`)
    REFERENCES `mediamarktdb`.`landen` (`idland`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`producten` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `productnaam` VARCHAR(255) NULL,
  `prijs` DECIMAL(65,2) NULL,
  `leveranciers_idleverancier` INT NOT NULL,
  `categorieën_idcategorie` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `fk_producten_leveranciers1_idx` (`leveranciers_idleverancier` ASC) VISIBLE,
  INDEX `fk_producten_categorieën1_idx` (`categorieën_idcategorie` ASC) VISIBLE,
  CONSTRAINT `fk_producten_leveranciers1`
    FOREIGN KEY (`leveranciers_idleverancier`)
    REFERENCES `mediamarktdb`.`leveranciers` (`idleverancier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producten_categorieën1`
    FOREIGN KEY (`categorieën_idcategorie`)
    REFERENCES `mediamarktdb`.`categorieën` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`klanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`klanten` (
  `idklant` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(255) NULL,
  `achternaam` VARCHAR(255) NULL,
  `telefoon` INT NULL,
  `email` VARCHAR(255) NULL,
  `woonplaats` VARCHAR(255) NULL,
  `totaalbestellingen` INT NULL,
  `totaalproducten` INT NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB
COMMENT = '`';


-- -----------------------------------------------------
-- Table `mediamarktdb`.`bestellingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`bestellingen` (
  `idbestelling` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NULL,
  `totaalprijs` DECIMAL(65,2) NULL,
  `klanten_idklant` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idbestelling`),
  INDEX `fk_bestellingen_klanten1_idx` (`klanten_idklant` ASC) VISIBLE,
  CONSTRAINT `fk_bestellingen_klanten1`
    FOREIGN KEY (`klanten_idklant`)
    REFERENCES `mediamarktdb`.`klanten` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`bestellingen_has_producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`bestellingen_has_producten` (
  `bestellingen_idbestelling` INT NOT NULL,
  `producten_idproduct` INT NOT NULL,
  PRIMARY KEY (`bestellingen_idbestelling`, `producten_idproduct`),
  INDEX `fk_bestellingen_has_producten_producten1_idx` (`producten_idproduct` ASC) VISIBLE,
  INDEX `fk_bestellingen_has_producten_bestellingen1_idx` (`bestellingen_idbestelling` ASC) VISIBLE,
  CONSTRAINT `fk_bestellingen_has_producten_bestellingen1`
    FOREIGN KEY (`bestellingen_idbestelling`)
    REFERENCES `mediamarktdb`.`bestellingen` (`idbestelling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bestellingen_has_producten_producten1`
    FOREIGN KEY (`producten_idproduct`)
    REFERENCES `mediamarktdb`.`producten` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`productklachten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`productklachten` (
  `idproductklachten` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(255) NULL,
  `achternaam` VARCHAR(255) NULL,
  `telefoon` INT(20) NULL,
  `email` VARCHAR(255) NULL,
  `gender` VARCHAR(255) NULL,
  `product` VARCHAR(255) NULL,
  `oplossing` VARCHAR(255) NULL,
  PRIMARY KEY (`idproductklachten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`medewerkerklachten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`medewerkerklachten` (
  `idmedewerkerklachten` INT NOT NULL AUTO_INCREMENT,
  `volledigenaam` VARCHAR(255) NULL,
  `straatnaam` VARCHAR(255) NULL,
  `huisnummer` VARCHAR(255) NULL,
  `klachtdatum` DATE NULL,
  `contactmanier` VARCHAR(255) NULL,
  `medewerker` VARCHAR(255) NULL,
  `probleem` VARCHAR(255) NULL,
  `oplossing` VARCHAR(255) NULL,
  PRIMARY KEY (`idmedewerkerklachten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`websiteklachten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`websiteklachten` (
  `idwebsiteklachten` INT NOT NULL AUTO_INCREMENT,
  `volledigenaam` VARCHAR(255) NULL,
  `telefoon` INT(20) NULL,
  `postcode` VARCHAR(255) NULL,
  `gender` VARCHAR(255) NULL,
  `probleem` VARCHAR(255) NULL,
  `oplossing` VARCHAR(255) NULL,
  PRIMARY KEY (`idwebsiteklachten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamarktdb`.`complimenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamarktdb`.`complimenten` (
  `idcomplimenten` INT NOT NULL AUTO_INCREMENT,
  `volledigenaam` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `woonplaats` VARCHAR(255) NULL,
  `geboortedatum` DATE NULL,
  `compliment` VARCHAR(255) NULL,
  `extra` VARCHAR(255) NULL,
  PRIMARY KEY (`idcomplimenten`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
